import = ["/home/javier/.config/alacritty/themes/onedark.toml"]
live_config_reload = true

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 7

[font.bold]
family = "Jet Brains Mono Nerd Font"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Jet Brains Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Jet Brains Mono Nerd Font"
style = "Light"

[font.offset]
x = 0
y = 0

[window]
opacity = 1
startup_mode = "Windowed"

[window.dimensions]
columns = 90
lines = 26

[window.padding]
x = 6
y = 3
